version: '3.1'

services:
  wordpress:
    image: wordpress:5.8
    restart: always
    ports:
      - 8082:80
    environment:
      WORDPRESS_DB_HOST: mariadb-root
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: central_root_password
      WORDPRESS_DB_NAME: restaurant_db
    volumes:
      - .:/var/www/html
    networks:
      - shared-network

networks:
  shared-network:
    external: true
